import Head from "next/head";
import { NavigationBar } from "@/components/NavigationBar";

export default function Home() {
  return (<>
      <Head>
          <title>In & Out Board</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="mainContainer">
          <NavigationBar />
    </main>
  </>
  );
}
